

const today = new Date();

function dateKey({offsetDays} :any) {
  const d = new Date(today);
  d.setDate(today.getDate() + offsetDays);
  return d.toISOString().split('T')[0]; 
}

export const mockTasks = [
  {
    id: 1,
    date: dateKey(0),
    title: 'Fix login screen bug',
    desc: 'Auth flow crashes on empty email',
    priority: 'high',
    category: 'Work',
    done: false,
  },
  {
    id: 2,
    date: dateKey(0),
    title: 'Review PR #42',
    desc: "Team's new feature branch",
    priority: 'medium',
    category: 'Work',
    done: true,
  },
  {
    id: 3,
    date: dateKey(0),
    title: 'Buy groceries',
    desc: 'Milk, eggs, bread, coffee',
    priority: 'low',
    category: 'Personal',
    done: false,
  },
  {
    id: 4,
    date: dateKey(0),
    title: '30 min workout',
    desc: 'Chest + triceps day',
    priority: 'medium',
    category: 'Health',
    done: true,
  },
  {
    id: 5,
    date: dateKey(0),
    title: 'Read React Native docs',
    desc: 'FlatList and ScrollView section',
    priority: 'high',
    category: 'Learning',
    done: false,
  },
  {
    id: 6,
    date: dateKey(1),
    title: 'Write unit tests',
    desc: 'Cover the new utils functions',
    priority: 'high',
    category: 'Work',
    done: false,
  },
  {
    id: 7,
    date: dateKey(1),
    title: 'Call mom',
    desc: 'Sunday catch-up',
    priority: 'medium',
    category: 'Personal',
    done: false,
  },
  {
    id: 8,
    date: dateKey(1),
    title: 'Update resume',
    desc: 'Add latest project experience',
    priority: 'low',
    category: 'Personal',
    done: false,
  },
  {
    id: 9,
    date: dateKey(1),
    title: 'Team standup prep',
    desc: 'List blockers and updates',
    priority: 'medium',
    category: 'Work',
    done: false,
  },
  {
    id: 10,
    date: dateKey(1),
    title: 'Watch RN navigation tutorial',
    desc: 'Stack + Tab navigator basics',
    priority: 'low',
    category: 'Learning',
    done: false,
  },
  {
    id: 11,
    date: dateKey(2),
    title: 'Deploy hotfix to staging',
    desc: 'Critical payment bug',
    priority: 'high',
    category: 'Work',
    done: false,
  },
  {
    id: 12,
    date: dateKey(2),
    title: 'Drink 8 glasses of water',
    desc: 'Stay hydrated all day',
    priority: 'low',
    category: 'Health',
    done: false,
  },
  {
    id: 13,
    date: dateKey(2),
    title: 'Design new onboarding flow',
    desc: 'Sketch 3 variations',
    priority: 'medium',
    category: 'Work',
    done: false,
  },
  {
    id: 14,
    date: dateKey(2),
    title: 'Cancel unused subscriptions',
    desc: 'Check bank statement',
    priority: 'low',
    category: 'Personal',
    done: false,
  },
  {
    id: 15,
    date: dateKey(3),
    title: 'Set up AsyncStorage',
    desc: 'Persist todos between sessions',
    priority: 'high',
    category: 'Learning',
    done: false,
  },
  {
    id: 16,
    date: dateKey(3),
    title: 'Client presentation slides',
    desc: 'Q2 product roadmap',
    priority: 'high',
    category: 'Work',
    done: false,
  },
  {
    id: 17,
    date: dateKey(3),
    title: 'Evening walk',
    desc: '30 mins around the park',
    priority: 'low',
    category: 'Health',
    done: false,
  },
  {
    id: 18,
    date: dateKey(3),
    title: 'Learn FlatList optimization',
    desc: 'keyExtractor + getItemLayout',
    priority: 'medium',
    category: 'Learning',
    done: false,
  },
  {
    id: 19,
    date: dateKey(4),
    title: 'Code review for juniors',
    desc: '3 open PRs to review',
    priority: 'medium',
    category: 'Work',
    done: false,
  },
  {
    id: 20,
    date: dateKey(4),
    title: 'Doctor appointment',
    desc: 'Annual health checkup at 11am',
    priority: 'high',
    category: 'Health',
    done: false,
  },
  {
    id: 21,
    date: dateKey(4),
    title: 'Refactor API service layer',
    desc: 'Move to axios interceptors',
    priority: 'medium',
    category: 'Work',
    done: false,
  },
  {
    id: 22,
    date: dateKey(5),
    title: 'Plan weekend trip',
    desc: 'Manali or Rishikesh — decide',
    priority: 'low',
    category: 'Personal',
    done: false,
  },
  {
    id: 23,
    date: dateKey(5),
    title: 'Implement push notifications',
    desc: 'Firebase setup for RN',
    priority: 'high',
    category: 'Learning',
    done: false,
  },
  {
    id: 24,
    date: dateKey(6),
    title: 'Weekly retrospective',
    desc: "What went well, what didn't",
    priority: 'medium',
    category: 'Work',
    done: false,
  },
  {
    id: 25,
    date: dateKey(6),
    title: 'Meditate 10 minutes',
    desc: 'Morning routine',
    priority: 'low',
    category: 'Health',
    done: false,
  },
];
